baseURL = "https://arewewaylandyet.com/"
languageCode = "en-us"
title = "Are we Wayland yet?"

disableKinds = ["taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

assetDir = "src"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  noJSConfigInAssets = true